import { BreathingTechnique } from '../../types/Breathing';

export const BREATHING_TECHNIQUES: BreathingTechnique[] = [
  {
    id: 'box',
    name: 'Box Breathing',
    description: 'Enhances focus and reduces stress',
    inhale: 4,
    hold: 4,
    exhale: 4,
    holdAfterExhale: 4,
    icon: 'BOX',
    category: 'focus',
    difficulty: 'Intermediate',
    benefits: [
      'Improves concentration',
      'Reduces stress levels',
      'Enhances mental clarity',
      'Calms the nervous system',
    ],
  },
  {
    id: '478',
    name: '4-7-8 Breathing',
    description: 'Promotes relaxation and helps you fall asleep',
    inhale: 4,
    hold: 7,
    exhale: 8,
    icon: '478',
    category: 'relaxation',
    difficulty: 'Beginner',
    benefits: [
      'Reduces anxiety and stress',
      'Helps you fall asleep faster',
      'Lowers heart rate',
      'Promotes deep relaxation',
    ],
  },
  {
    id: 'deep',
    name: 'Deep Breathing',
    description: 'Calms the mind and relieves tension',
    inhale: 6,
    hold: 2,
    exhale: 6,
    icon: 'DEEP',
    category: 'stress-relief',
    difficulty: 'Beginner',
    benefits: [
      'Relieves muscle tension',
      'Lowers blood pressure',
      'Reduces stress hormones',
      'Increases oxygen flow',
    ],
  },
  {
    id: 'alternate-nostril',
    name: 'Alternate Nostril',
    description: 'Balances left and right brain hemispheres',
    inhale: 4,
    hold: 4,
    exhale: 4,
    icon: 'AN',
    category: 'relaxation',
    difficulty: 'Intermediate',
    benefits: [
      'Balances nervous system',
      'Reduces anxiety',
      'Improves focus',
      'Enhances mental clarity',
    ],
  },
  {
    id: 'belly',
    name: 'Belly Breathing',
    description: 'Engages diaphragm for deeper breaths',
    inhale: 5,
    hold: 0,
    exhale: 5,
    icon: 'BB',
    category: 'stress-relief',
    difficulty: 'Beginner',
    benefits: [
      'Reduces stress',
      'Lowers heart rate',
      'Improves oxygen intake',
      'Promotes relaxation',
    ],
  },
  {
    id: 'pursed-lip',
    name: 'Pursed Lip Breathing',
    description: 'Slows breathing and improves ventilation',
    inhale: 4,
    hold: 0,
    exhale: 6,
    icon: 'PL',
    category: 'stress-relief',
    difficulty: 'Beginner',
    benefits: [
      'Improves lung function',
      'Reduces shortness of breath',
      'Promotes calmness',
      'Easy to practice anywhere',
    ],
  },
  {
    id: 'equal',
    name: 'Equal Breathing',
    description: 'Balances inhale and exhale durations',
    inhale: 5,
    hold: 0,
    exhale: 5,
    icon: 'EQ',
    category: 'focus',
    difficulty: 'Beginner',
    benefits: [
      'Balances mind and body',
      'Reduces stress',
      'Improves concentration',
      'Promotes mental clarity',
    ],
  },
  {
    id: 'resonant',
    name: 'Resonant Breathing',
    description: 'Breathing at 5 breaths per minute',
    inhale: 6,
    hold: 0,
    exhale: 6,
    icon: 'RB',
    category: 'relaxation',
    difficulty: 'Intermediate',
    benefits: [
      'Maximizes heart rate variability',
      'Reduces stress',
      'Improves cardiovascular health',
      'Enhances emotional balance',
    ],
  },
  {
    id: 'sitali',
    name: 'Sitali Breath',
    description: 'Cooling breath technique from yoga',
    inhale: 5,
    hold: 2,
    exhale: 5,
    icon: 'ST',
    category: 'relaxation',
    difficulty: 'Intermediate',
    benefits: [
      'Cools the body',
      'Reduces anger',
      'Lowers blood pressure',
      'Calms the mind',
    ],
  },
  {
    id: 'lions',
    name: 'Lion\'s Breath',
    description: 'Energizing breath with forceful exhale',
    inhale: 4,
    hold: 0,
    exhale: 6,
    icon: 'LB',
    category: 'stress-relief',
    difficulty: 'Beginner',
    benefits: [
      'Releases tension',
      'Energizes the body',
      'Relieves stress',
      'Strengthens vocal cords',
    ],
  },
  {
    id: 'wim-hof',
    name: 'Wim Hof Method',
    description: 'Power breathing for energy and focus',
    inhale: 2,
    hold: 15,
    exhale: 2,
    icon: 'WH',
    category: 'focus',
    difficulty: 'Advanced',
    benefits: [
      'Boosts energy levels',
      'Strengthens immune system',
      'Improves mental focus',
      'Increases oxygen delivery',
    ],
  },
  {
    id: 'coherent',
    name: 'Coherent Breathing',
    description: 'Five breaths per minute for balance',
    inhale: 6,
    hold: 0,
    exhale: 6,
    icon: 'CB',
    category: 'relaxation',
    difficulty: 'Intermediate',
    benefits: [
      'Reduces anxiety',
      'Improves sleep quality',
      'Enhances heart health',
      'Promotes emotional balance',
    ],
  },
  {
    id: 'triangle',
    name: 'Triangle Breathing',
    description: 'Three equal phases of breathing',
    inhale: 4,
    hold: 4,
    exhale: 4,
    icon: 'TB',
    category: 'focus',
    difficulty: 'Beginner',
    benefits: [
      'Improves focus',
      'Reduces stress',
      'Easy to remember',
      'Promotes calmness',
    ],
  },
  {
    id: 'humming-bee',
    name: 'Humming Bee Breath',
    description: 'Calming breath with humming sound',
    inhale: 5,
    hold: 0,
    exhale: 7,
    icon: 'HB',
    category: 'relaxation',
    difficulty: 'Beginner',
    benefits: [
      'Reduces anger and anxiety',
      'Lowers blood pressure',
      'Improves concentration',
      'Promotes inner peace',
    ],
  },
  {
    id: 'kapalbhati',
    name: 'Skull Shining Breath',
    description: 'Rapid breathing for cleansing',
    inhale: 1,
    hold: 0,
    exhale: 1,
    icon: 'KP',
    category: 'focus',
    difficulty: 'Advanced',
    benefits: [
      'Cleanses respiratory system',
      'Energizes the body',
      'Improves digestion',
      'Enhances mental clarity',
    ],
  },
  {
    id: 'custom',
    name: 'Custom Pattern',
    description: 'Create your own breathing rhythm',
    inhale: 4,
    hold: 4,
    exhale: 4,
    icon: '+',
    category: 'custom',
    difficulty: 'Advanced',
    benefits: [
      'Personalized breathing practice',
      'Adapt to your needs',
      'Experiment with different rhythms',
    ],
  },
];
